ci: update CD

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -13,7 +13,7 @@ on:
 env:
   AZURE_WEBAPP_NAME: minicrm-bobiasg-docker    # set this to your application's name
   REGISTRY: ghcr.io
-  SHA: ${git rev-parse --short HEAD}
+  # SHA: ${git rev-parse --short HEAD}
 
 jobs:
 #  approve:
@@ -119,13 +119,22 @@ jobs:
       run: |
         calculatedSha=$(git rev-parse --short ${{ github.sha }})
         echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
-  
+
+    - name: Check if image exists
+      id: check-image
+      run: |
+        IMAGE_NAME="${{ github.event_name == 'workflow_run' && github.event.workflow_run.outputs.image_name || format('{0}/{1}:sha-{2}', env.REGISTRY, github.repository, env.COMMIT_SHORT_SHA) }}"
+        if ! docker pull $IMAGE_NAME; then
+          echo "::error::Image $IMAGE_NAME does not exist."
+          exit 1
+        fi
+
+        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
+        
     - name: 'Deploy to Azure WebApp'      
       id: deploy-to-container
-      env: 
-        IMAGE_NAME: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.outputs.image_name || format('{0}/{1}:sha-{2}', env.REGISTRY, github.repository, env.COMMIT_SHORT_SHA) }}
       uses: azure/webapps-deploy@v3
       with:
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
-        images: ${{ env.image_name}}
+        images: ${{ env.IMAGE_NAME}}
